server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://192.168.42.113:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example: DEBUG
