apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld-container
          image: 192.168.42.113:5000/001-springboot-demo-helloworld:47
          args: ["--server.ssl.client-auth=none"]
          ports:
            - containerPort: 8443
