apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 443 # 前端访问的端口
      targetPort: 8443 # Spring Boot 应用监听的端口
