{{- if .Values.deployApp1 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-helm-deployment-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-helm-deployment-app1
  template:
    metadata:
      labels:
        app: helloworld-helm-deployment-app1
    spec:
      containers:
        - name: helloworld-container
          image: 192.168.42.113:5000/001-springboot-demo-helloworld:49 # 替换为你的镜像名和标签
          args: ["--server.ssl.client-auth=none","--server.servlet.context-path=/app1"]
          ports:
            - containerPort: 8443
{{- end }}
