server:
  port: 8092
  ssl:
    enabled: true
    key-store: D:\IdeaProjects\spring-demos\004-springboot-demo-auth\src\main\resources\cert\myssl.p12
    key-store-password: changeit
    keyStoreType: JKS
    keyAlias: myssl
    trust-store: classpath:truststore.jks
    trust-store-password: changeit
    trust-store-type: JKS
