server:
  port: 8443
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:cert/server.p12
    key-store-password: changeit
    keyStoreType: JKS
    #keyAlias: tomcat
    trust-store: classpath:cert/truststore.jks
    trust-store-password: changeit
