server:
  port: 8443
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:keystore.p12
    key-store-password: changeit
    keyStoreType: JKS
    keyAlias: tomcat
    trust-store: classpath:truststore.p12
    trust-store-password: yourpassword
