server:
  port: 8091
  ssl:
    enabled: true
    client-auth: none
    key-store: classpath:server.p12
    key-store-password: changeit
    keyStoreType: JKS
    keyAlias: tomcat
    trust-store: classpath:truststore.jks
    trust-store-password: changeit
